/Config/createRole:
  post:
    summary: Create a new role
    tags:
      - Configuration
    requestBody:
      description: Data for creating a new role
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateRoleDto"
    responses:
      "200":
        description: Role created successfully
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoleEntity"
      "400":
        description: Bad Request
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                message:
                  type: string
      "500":
        description: Internal Server Error
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                message:
                  type: string

components:
  schemas:
    CreateRoleDto:
      type: object
      required:
        - role_key
        - role_desc
      properties:
        role_key:
          type: string
        role_desc:
          type: string

    RoleEntity:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        data:
          $ref: "#/components/schemas/RoleEntity"
        role_key:
          type: string
        role_desc:
          type: string
